apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    role: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.repository }}:{{ .Values.frontend.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.frontend.port }}