name: CI Backend

on:
  push:
    branches: [ main ]
    
    paths-ignore:
        - README.md
        - helm/helm_charts/values.yaml
      
jobs:
  trivy-fs-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Trivy File System Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './mern/backend'
          trivy-config: trivy.yaml

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

  sast:
    needs: trivy-fs-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install nodejsscan
        run: pip install nodejsscan

      - name: Run SAST Scan
        run: |
          nodejsscan -d mern/backend -o backend-sast-report.json
          cat backend-sast-report.json

      - name: Upload SAST Report
        uses: actions/upload-artifact@v4
        with:
          name: backend-sast-report
          path: backend-sast-report.json

  docker-build-push:
    name: Build & Push Backend Docker Image
    runs-on: ubuntu-latest
    needs: sast
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./mern/backend
          file: ./mern/backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.run_id }}

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.run_id }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
