name: CI Deployment

on:
  push:
    branches: [ main ]
    
    paths-ignore:
        - README.md
        - helm/helm_charts/values.yaml

jobs:
  docker-build-push-frontend:
    name: Build & Push Frontend Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./mern/frontend
          file: ./mern/frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.run_id }}

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.run_id }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true

  docker-build-push-backend:
    name: Build & Push Backend Docker Image
    runs-on: ubuntu-latest
    needs: docker-build-push-frontend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./mern/backend
          file: ./mern/backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.run_id }}

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.run_id }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
  
  update-helm-tags:
    runs-on: ubuntu-latest
    needs: [docker-build-push-frontend, docker-build-push-backend]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update Frontend and Backend Tags in Helm Chart
        run: |
          sed -i '/backend:/,/tag:/s/tag:.*/tag: "${{ github.run_id }}"/' helm/helm_charts/values.yaml
          
          sed -i '/frontend:/,/tag:/s/tag:.*/tag: "${{ github.run_id }}"/' helm/helm_charts/values.yaml

      - name: Commit and Push Changes
        run: |
          git config --global user.name "Ayushgittt"
          git config --global user.email "bhandariayush960@gmail.com"

          git add helm/helm_charts/values.yaml
          git commit -m "Update frontend and backend tags to ${{ github.run_id }}"
          git push