name: CI Pipeline - Frontend (React)

on:
  push:
    branches: [ main ]
    
    paths-ignore:
        - README.md
        - helm/helm_charts/values.yaml

jobs:
  trivy-fs-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Trivy File System Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './mern/frontend'
          trivy-config: trivy.yaml

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

  sast:
    needs: trivy-fs-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install nodejsscan
        run: pip install nodejsscan

      - name: Run SAST Scan
        run: |
          nodejsscan -d mern/frontend -o frontend-sast-report.json
          cat frontend-sast-report.json

      - name: Upload SAST Report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-sast-report
          path: frontend-sast-report.json

  docker-build-push:
    name: Build & Push Frontend Docker Image
    runs-on: ubuntu-latest
    needs: sast
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./mern/frontend
          file: ./mern/frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mern-frontend:${{ github.run_id }}

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/mern-frontend:${{ github.run_id }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true

  update-helm-tag:
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update Frontend Tag in Helm Chart
        run: |
          sed -i '/frontend:/,/tag:/s/tag:.*/tag: "${{ github.run_id }}"/' helm/helm_charts/values.yaml

      - name: Commit and Push
        run: |
          git config --global user.email "bhandariayush960@gmail.com"
          git config --global user.name "Ayushgittt"
          git add helm/helm_charts/values.yaml
          git commit -m "Update frontend tag"
          git push
